id: P007005
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24218
  title: བདག་འཛིན་གཤགས་འདེབས་རྩ་འགྲེལ།
  author: ''
  volumes:
    31f57ee1e63f4ec0972fbc99f8093240:
      image_group_id: I1KG24295
      title: ''
      volume_number: 1
      total_pages: 224
ebook_metadata:
  title: བདག་འཛིན་གཤགས་འདེབས་རྩ་འགྲེལ།
  author: ''
  sku: P007005
  cover: cover.jpg
  layers:
  - pagination
