id: P007005
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:35:40.310028
source_metadata:
  id: bdr:W1KG24218
  title: བདག་འཛིན་གཤགས་འདེབས་རྩ་འགྲེལ།
  author: ''
  volumes:
    0340b96bd8124313939b6057e78bd558:
      image_group_id: I1KG24295
      title: Volume 1 of bdag 'dzin gshags 'debs rtsa 'grel/
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
