id: IA723D83A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:52:40+00:00'
last_modified: '2022-06-08T11:53:32.609412+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24218
  title: བདག་འཛིན་གཤགས་འདེབས་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0B04:
      image_group_id: I1KG24295
      title: Volume 1 of bdag 'dzin gshags 'debs rtsa 'grel/
      total_pages: 224
      order: 1
      base_file: 0B04.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
